// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.count")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.buckets")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.buckets3")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.contract")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.device")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.directout")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.farmerkey")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.finaldir")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.level")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.memory")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.multifinaldir")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.ndevices")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.nftplot")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.pin_memory")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.plotter")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.poolkey")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.priority")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.rmulti2")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.size")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.stagedir")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.streams")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.threads")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.tmpdir")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.tmpdir2")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.tmpdir3")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.tmptoggle")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.waitforcopy")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.chunksize")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mmx.Gui.Win.Common.Plotter.PlotterOptionsItems.ssdplot")]
