//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mmx.Gui.Win.Wpf.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mmx.Gui.Win.Wpf.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of this program is already running by other user.
        /// </summary>
        public static string Another_Instance_Running {
            get {
                return ResourceManager.GetString("Another_Instance_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string Console_Title {
            get {
                return ResourceManager.GetString("Console_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Harvester_Add {
            get {
                return ResourceManager.GetString("Harvester_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Harvester.
        /// </summary>
        public static string Harvester_Reload {
            get {
                return ResourceManager.GetString("Harvester_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Harvester_Remove {
            get {
                return ResourceManager.GetString("Harvester_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvester.
        /// </summary>
        public static string Harvester_Title {
            get {
                return ResourceManager.GetString("Harvester_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load plots from:.
        /// </summary>
        public static string harvesterPlots {
            get {
                return ResourceManager.GetString("harvesterPlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available!.
        /// </summary>
        public static string New_Version_Available {
            get {
                return ResourceManager.GetString("New_Version_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.
        /// </summary>
        public static string Node_Title {
            get {
                return ResourceManager.GetString("Node_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of buckets.
        /// </summary>
        public static string Plotter_buckets {
            get {
                return ResourceManager.GetString("Plotter_buckets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of buckets for phase 3+4.
        /// </summary>
        public static string Plotter_buckets3 {
            get {
                return ResourceManager.GetString("Plotter_buckets3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buckets.
        /// </summary>
        public static string Plotter_BucketsHeader {
            get {
                return ResourceManager.GetString("Plotter_BucketsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Plotter_Close {
            get {
                return ResourceManager.GetString("Plotter_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line.
        /// </summary>
        public static string Plotter_CommandLine {
            get {
                return ResourceManager.GetString("Plotter_CommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool Contract Address (62 chars).
        /// </summary>
        public static string Plotter_contract {
            get {
                return ResourceManager.GetString("Plotter_contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of plots to create.
        /// </summary>
        public static string Plotter_count {
            get {
                return ResourceManager.GetString("Plotter_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories.
        /// </summary>
        public static string Plotter_DirectoriesTab {
            get {
                return ResourceManager.GetString("Plotter_DirectoriesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create plot directly in finaldir.
        /// </summary>
        public static string Plotter_directout {
            get {
                return ResourceManager.GetString("Plotter_directout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        public static string Plotter_Do_You_Want_To_Continue {
            get {
                return ResourceManager.GetString("Plotter_Do_You_Want_To_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmer Public Key (48 bytes).
        /// </summary>
        public static string Plotter_farmerkey {
            get {
                return ResourceManager.GetString("Plotter_farmerkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final directory to copy plot in parallel.
        /// </summary>
        public static string Plotter_finaldir {
            get {
                return ResourceManager.GetString("Plotter_finaldir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Plotter_GeneralTab {
            get {
                return ResourceManager.GetString("Plotter_GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys.
        /// </summary>
        public static string Plotter_KeysTab {
            get {
                return ResourceManager.GetString("Plotter_KeysTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create NFT plot.
        /// </summary>
        public static string Plotter_nftplot {
            get {
                return ResourceManager.GetString("Plotter_nftplot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Plotter_Pause {
            get {
                return ResourceManager.GetString("Plotter_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfomance.
        /// </summary>
        public static string Plotter_PerfomanceTab {
            get {
                return ResourceManager.GetString("Plotter_PerfomanceTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool Public Key (48 bytes).
        /// </summary>
        public static string Plotter_poolkey {
            get {
                return ResourceManager.GetString("Plotter_poolkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Plotter_priority {
            get {
                return ResourceManager.GetString("Plotter_priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string Plotter_ProcessHeader {
            get {
                return ResourceManager.GetString("Plotter_ProcessHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Plotter_Resume {
            get {
                return ResourceManager.GetString("Plotter_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread multiplier for P2.
        /// </summary>
        public static string Plotter_rmulti2 {
            get {
                return ResourceManager.GetString("Plotter_rmulti2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K size.
        /// </summary>
        public static string Plotter_size {
            get {
                return ResourceManager.GetString("Plotter_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot size.
        /// </summary>
        public static string Plotter_SizeHeader {
            get {
                return ResourceManager.GetString("Plotter_SizeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage directory to write plot file.
        /// </summary>
        public static string Plotter_stagedir {
            get {
                return ResourceManager.GetString("Plotter_stagedir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Plotter_Start {
            get {
                return ResourceManager.GetString("Plotter_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Plotter_Stop {
            get {
                return ResourceManager.GetString("Plotter_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of threads.
        /// </summary>
        public static string Plotter_threads {
            get {
                return ResourceManager.GetString("Plotter_threads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads.
        /// </summary>
        public static string Plotter_ThreadsHeader {
            get {
                return ResourceManager.GetString("Plotter_ThreadsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plotter.
        /// </summary>
        public static string Plotter_Title {
            get {
                return ResourceManager.GetString("Plotter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary directory.
        /// </summary>
        public static string Plotter_tmpdir {
            get {
                return ResourceManager.GetString("Plotter_tmpdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary directory 2 [RAM].
        /// </summary>
        public static string Plotter_tmpdir2 {
            get {
                return ResourceManager.GetString("Plotter_tmpdir2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate tmpdir/tmpdir2.
        /// </summary>
        public static string Plotter_tmptoggle {
            get {
                return ResourceManager.GetString("Plotter_tmptoggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for copy to start next plot.
        /// </summary>
        public static string Plotter_waitforcopy {
            get {
                return ResourceManager.GetString("Plotter_waitforcopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, stop plotting.
        /// </summary>
        public static string Plotter_Yes_Stop_Plotting {
            get {
                return ResourceManager.GetString("Plotter_Yes_Stop_Plotting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string Settings_CheckForUpdates {
            get {
                return ResourceManager.GetString("Settings_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close to notification area.
        /// </summary>
        public static string Settings_CloseToNotification {
            get {
                return ResourceManager.GetString("Settings_CloseToNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation on exit.
        /// </summary>
        public static string Settings_ConfirmationOnExit {
            get {
                return ResourceManager.GetString("Settings_ConfirmationOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Settings_Debug {
            get {
                return ResourceManager.GetString("Settings_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable OpenCL.
        /// </summary>
        public static string Settings_DisableOpenCL {
            get {
                return ResourceManager.GetString("Settings_DisableOpenCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inhibit system sleep.
        /// </summary>
        public static string Settings_InhibitSystemSleep {
            get {
                return ResourceManager.GetString("Settings_InhibitSystemSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to notification area.
        /// </summary>
        public static string Settings_MinimizeToNotification {
            get {
                return ResourceManager.GetString("Settings_MinimizeToNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string Settings_Network {
            get {
                return ResourceManager.GetString("Settings_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification area.
        /// </summary>
        public static string Settings_NotificationArea {
            get {
                return ResourceManager.GetString("Settings_NotificationArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Management.
        /// </summary>
        public static string Settings_PowerManagement {
            get {
                return ResourceManager.GetString("Settings_PowerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Console.
        /// </summary>
        public static string Settings_ShowConsole {
            get {
                return ResourceManager.GetString("Settings_ShowConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in notification area.
        /// </summary>
        public static string Settings_ShowInNotifitation {
            get {
                return ResourceManager.GetString("Settings_ShowInNotifitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start minimized.
        /// </summary>
        public static string Settings_StartMinimized {
            get {
                return ResourceManager.GetString("Settings_StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start on Windows start up.
        /// </summary>
        public static string Settings_StartOnStartup {
            get {
                return ResourceManager.GetString("Settings_StartOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start up.
        /// </summary>
        public static string Settings_StartUp {
            get {
                return ResourceManager.GetString("Settings_StartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Settings_Update {
            get {
                return ResourceManager.GetString("Settings_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update interval.
        /// </summary>
        public static string Settings_UpdateInterval {
            get {
                return ResourceManager.GetString("Settings_UpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;how.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
